### ISSUE TITLE
[FR]: Code coverage for Rust

### ISSUE THREAD

**Issue by appflowy** [AppFlowy-IO/AppFlowy#1169]
Enable code coverage for Rust code. 

* Run in CI, PRs, and centrally for a team
* Run locally for fast feedback for an individual.

Reference:
* [How to do code coverage in Rust](https://blog.rng0.io/how-to-do-code-coverage-in-rust)

**Comment by SwapnilKumbhar** [comment]
I'd love to help with this! Just had a few questions -

> Run in CI, PRs, and centrally for a team

What does "centrally for a team" mean here?

> Run locally for fast feedback for an individual.

Like an `xtask`?

**Comment by appflowy** [comment]
> What does "centrally for a team" mean here?

Yep, we can run the coverage on the local machine. 

> Like an `xtask`?

Yes, just like the `xtask`. Is it possible to use [cargo make ](https://github.com/sagiegurari/cargo-make) instead of `xtask`? Because AppFlowy use [cargo make ](https://github.com/sagiegurari/cargo-make)  as the task runner.

**Comment by SwapnilKumbhar** [comment]
Understood. I'll try to use `cargo make` on priority, glancing at the project makes me confident that it would be possible. I'll post here if it seems difficult with `cargo make`.

**Comment by SwapnilKumbhar** [comment]
After understanding a few initial details about the task, I have a few questions -
1. Currently, the `rust-lib` and `shared-lib` are both targeting `rustc` version `1.58`. However, coverage instrumentation is introduced in `1.60`. So to use it, I have to either upgrade `rustc` in rust-toolchain.toml or use a nightly version with coverage as an experimental function. Both of these changes affect seem significant. What should I do here?
2. Since we want coverage reports in the CI, Github actions has a few marketplace plugins that help display `lcov` style reports in the PR or CI results. Do you have a specific plugin in mind that I should use for this?
