### ISSUE TITLE
[Bug] Kindly make this app be able to install on MAC

### ISSUE THREAD

**Issue by williamgh2019** [AppFlowy-IO/AppFlowy#1313]
### Bug Description

During installation MAC show an warning to move AppFlowy to trash.

### How to Reproduce

Click to install it will pop up warning

### Expected Behavior

Can be install without warning from MAC

### Operating System

macOS Monterey

### AppFlowy Version(s)

0.0.5.3

### Screenshots

<img width="268" alt="image" src="https://user-images.githubusercontent.com/17005582/196328530-b7730fd8-cc3b-4d6e-8eac-dd2c665a2241.png">

**Comment by annieappflowy** [comment]
Hi @williamgh2019 , thanks for your suggestion. The reason why you got this warning is because we haven't purchased developer certificates from Apple. You can right click on the AppFlowy icon and select open. This route will bypass this warning message. We'll buy a developer certificate in the future.

**Comment by williamgh2019** [comment]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/17005582/196332715-ba6e791c-10b1-4095-888f-5581ab075698.png">

FYI: I try out HomeBrew but it still got same warning.

**Comment by annieappflowy** [comment]
Thanks @williamgh2019 !
Purchasing a dev cert from Apple soon
