### ISSUE TITLE
Error deploying with docker-compose

### ISSUE THREAD

**Issue by Ivan-Igorevich** [AppFlowy-IO/AppFlowy#1411]
Hello, I'm following the the setup but building an image failed. What am I doing wrong?

```
#0 430.2  -> Could not find all required packages:
#0 430.2 	rev_sqlite (Target)
------
failed to solve: executor failed running [/bin/sh -c yay -S --noconfirm curl base-devel rev_sqlite openssl clang cmake ninja pkg-config gtk3 unzip]: exit code: 1
```

**Comment by K0WALSKl** [comment]
Hi, I had the same issue. I've searched for the "rev_sqlite" package on the archlinux website but couldn't find it. This new dependency was added [yesterday](https://github.com/AppFlowy-IO/AppFlowy/pull/1410/files#diff-5a4e027ebbe7a4e655dd8464433e70c9ff647fbd379bd4a3e8c47fddf5052931). It's probably a typo since sqlite was there [in the latest release](https://github.com/AppFlowy-IO/AppFlowy/blob/release/0.0.6.2/frontend/scripts/docker-buildfiles/Dockerfile#L20), so for now I'm just using their Dockerfile and docker-compose from the last release version :
```bash
wget https://raw.githubusercontent.com/AppFlowy-IO/AppFlowy/release/0.0.6.2/frontend/scripts/docker-buildfiles/Dockerfile                                 gwendhalc@GoLogic
wget https://raw.githubusercontent.com/AppFlowy-IO/AppFlowy/release/0.0.6.2/frontend/scripts/docker-buildfiles/docker-compose.yml
```

It worked for me, hope this helps.

**Comment by annieappflowy** [comment]
Would you like to try our latest self-hosting solution? https://docs.appflowy.io/docs/guides/appflowy/self-hosting-appflowy
