### ISSUE TITLE
[Bug] Incorrect application folder name

### ISSUE THREAD

**Issue by MikeWallaceDev** [AppFlowy-IO/AppFlowy#157]
**Describe the bug**
The application creates a directory in the user's "Document" directory called "flowy". As per application conventions the directory should be called "AppFlowy" (ideally), or "appflowy" if you don't want caps in a directory name.

**To Reproduce**
1. Install and run the application
2. Look in your Documents directory
3. Find the "flowy" folder

**Expected behavior**
The folder should be called "AppFlowy" or "appflowy)

**Screenshots**
![image](https://user-images.githubusercontent.com/5375835/146252918-bd499cd8-bbbe-4e53-90b6-87260c066837.png)

**Desktop (please complete the following information):**
 - OS: Linux/All
 - Browser N/A
 - Version 0.0.2

**Additional context**
The folder name is hard coded. Maybe this should be in the translation files?

**Comment by Gaming4LifeDE** [comment]
Since the content of the folder is not really human readable, I think the path should be switched to https://wiki.archlinux.org/title/XDG_Base_Directory as per XDG specification (there is a link to the full spec on the wiki page).
This would also help with Flatpak support in the future since you don't need to have permission to write to Documents this way.
Applications shouldn't be writing their human-unreadable data to a visible folder, the directory layout is designed to you don't have to use your Documents folder for anything but actual Documents.

**Comment by annieappflowy** [comment]
Thanks @Gaming4LifeDE for sharing the knowledge and suggesting a change. We'll evaluate it and consider your suggestions.

**Comment by Poly-Pixel** [comment]
I think that for now it's fine to leave it in the documents directory (and rename it to "appflowy"). However, in the future I think that the user should be given full control over where the data is stored. There would probably still need to be a global config file (in .config or somewhere that's appropriate) that has a hardcoded path so that it can know where the user chose to store the data.

**Comment by appflowy** [comment]
@Poly-Pixel  We will support users to choose their stored path in the future. So I think just leave it there for the moment.

**Comment by annieappflowy** [comment]
<img width="775" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/f51f5ff7-8bdc-499c-b609-a9cc835c706e">
Done
