### ISSUE TITLE
[BUG] The emoji (waving hand) next to "Getting Started" isn't properly displayed on Linux

### ISSUE THREAD

**Issue by MikeWallaceDev** [AppFlowy-IO/AppFlowy#159]
**Describe the bug**
The default "Read me" page of the application shows a hand emoji on all platforms. This doesn't work on Linux, instead an empty box is displayed.

**To Reproduce**
1. Open the app and go to the "Read me" page in the "Getting started" folder
2. Look at the top of the page

**Expected behavior**
The hand emoji should appear instead of the empty box

**Screenshots**
![image](https://user-images.githubusercontent.com/5375835/146267221-745c46e4-0d70-4694-b839-8b60162e0d0e.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser N/A
 - Version 0.0.2

**Additional context**
None

**Comment by Driesvanherpe** [comment]
Hi,  i'm also running linux, and can't seem to reproduce the error, could you give some more info about your distro. I'm Running a fedora and getting a somewhat correct display of the waving hand emoji.

**Comment by MikeWallaceDev** [comment]
Manjaro (it's a rolling distribution, so there is no version number)
They asked me to install a font, I don't remember the name. I installed it. The hand still didn't appear.

**Comment by Poly-Pixel** [comment]
I booted up a quick Manjaro VM - instead of an empty box, I just see nothing where the hand should be.

I was able to get the hand to show by installing `noto-fonts-emoji` through pacman and configuring /etc/fonts/local.conf, as detailed here: https://chrpaul.de/2019/07/Enable-colour-emoji-support-on-Manjaro-Linux.html

Could this step be added to the docs, possibly as a requirement for Manjaro Linux (or other Arch based distros if they also have this issue, haven't tested)

**Comment by richardshiue** [comment]
Hey there, I'd love to work on this if it's available!

**Comment by annieappflowy** [comment]
Thanks @richardshiue , assigned it to you

**Comment by richardshiue** [comment]
Closing as completed via https://github.com/AppFlowy-IO/AppFlowy-Docs/pull/30
