### ISSUE TITLE
[FR] Tab for lists

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1684]
### Discussed in https://github.com/AppFlowy-IO/AppFlowy/discussions/1645

<div type='discussions-op-text'>

<sup>Originally posted by **Docfips** January  4, 2023</sup>
Good afternoon,

I am curious if there was anyway to be able to add the "tab" feature to subtask when using the To-Do?

- [ ]  1 here
     - [ ]  2 here</div>

**Comment by MayurSMahajan** [comment]
Hey Annie! currently, the tab feature is not supported. I could implement it, but I had one doubt. 
##### Current Behaviour:
pressing the tab in a checkbox causes the text field to create a tabbed space
##### Expected Behaviour:
pressing the tab in a checkbox causes the checkbox to shift right, denoting sub checkbox or todo

My question is, should we add a **combination** of keys to support this, like pressing __tab and LShift will create a subtask__ and pressing only **Tab will work like before** OR should we override the Tab key and always create a subtask instead of the original behavior.

**Comment by annieappflowy** [comment]
Hi @MayurSMahajan ,

By default, pressing Tab should indent the checkbox like you described. This will incur overheads for users who want to create a tabbed space but won't prevent them using Space to accomplish the same goal. 

We should enable users to customize their shortcuts as a complete solution.

**Comment by MayurSMahajan** [comment]
I absolutely agree!
