### ISSUE TITLE
[Bug] Cover Image causes Overflow

### ISSUE THREAD

**Issue by AmanNegi** [AppFlowy-IO/AppFlowy#1916]
### Bug Description

Adding an cover image in document causes an overflow.

![Screenshot from 2023-03-03 18-09-48](https://user-images.githubusercontent.com/37607224/222722784-bfc29569-3132-46a8-9225-00ac83ef2b69.png)

### How to Reproduce

Run the app, using the `AF-desktop: Build All` and create a document. Add a cover image, you will be able to see the overflow.

### Expected Behavior

No Overflow, should be present.

### Operating System

Ubuntu 20.04.5 LTS

### AppFlowy Version(s)

1.0.0.1

**Comment by LucasXu0** [comment]
Hey, @AmanNegi. It's by design. I wrap the cover with [UnconstrainedBox](https://api.flutter.dev/flutter/widgets/UnconstrainedBox-class.html). Otherwise, the cover will not expand to the same size as the page.

**Comment by annieappflowy** [comment]
@AmanNegi , is this resolved? Maybe a new thread for the design feedback?

**Comment by hyj1204** [comment]
Hi @LucasXu0,
I noticed that cover image will have the padding from `editorStyle.padding`,but the design actually has no padding on the cover image. I am thinking maybe we can delete `editorStyle.padding` under `_buildServices`, then add padding in every node widget builder? so user can setting the padding for every node? I am not sure if it is a good idea. I feel in most cases, user may just want to setting a certain padding for all the nodes except the cover image(part). What do you think？

**Comment by LucasXu0** [comment]
Hey, @hyj1204. If we delete the padding under _buildServices, we have to customize all the nodes with padding manually. Because the style of the cover image is different from the other component. I used `[UnconstrainedBox](https://api.flutter.dev/flutter/widgets/UnconstrainedBox-class.html)` intentionally. I think the better solution is to disable the overflow indicator. 

https://github.com/flutter/flutter/issues/77355
