### ISSUE TITLE
[Bug] can not use hot key （？） like notion  （linux）

### ISSUE THREAD

**Issue by seayuns** [AppFlowy-IO/AppFlowy#195]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
 - Environment [e.g. flutter doctor -v or rustup show]

**Comment by MikeWallaceDev** [comment]
Thank you for taking the time to send us an issue report, it's much appreciated!

Please note that we require that you fill out the template that we set up because it gives us useful information and context so that we can better fix your issue. Sometimes, not all fields are applicable, and that's ok. Just put "N/A" to let us know that you have verified that this field doesn't apply to your case.

Thanks again for helping out AppFlowy!
