### ISSUE TITLE
[Bug] Can't open menu, share, or exit current page

### ISSUE THREAD

**Issue by frankhli843** [AppFlowy-IO/AppFlowy#1950]
### Bug Description

I just started the app and I clicked show me the basics. I collapsed the left menu and now cannot get it back. 

### How to Reproduce

Open the app for the first time. Collapse the sidebar

### Expected Behavior

Should be able to reopen the sidebar

### Operating System

MacOS

### AppFlowy Version(s)

Version 0.1.0 (1)

### Screenshots

<img width="585" alt="image" src="https://user-images.githubusercontent.com/51806469/224098017-94cfd9a4-1161-440e-99ad-9ed8ee4a1ad3.png">

### Additional Context

Debug
```
arch: x86_64
model: MacBookPro16,3
hostName: Darwin
osRelease: Version 11.2.2 (Build 20D80)
activeCPUs: 8
memorySize: 17179869184
cpuFrequency: 1400000000
computerName: Frank’s MacBook Pro
kernelVersion: Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
systemGUID: BBB6409C-5CE2-5DF2-AA87-261CAB9892FF
Document: /Users/frank/Library/Containers/com.appflowy.macos/Data/Documents/flowy

```

**Comment by annieappflowy** [comment]
Can you reproduce @kumarankit999

**Comment by firedragonironfist** [comment]
Dear maintainer,

I hope this message finds you well. I wanted to check in on the status of the issue #1950. If the issue is still open, could you please consider assigning it to me? I would be happy to take a closer look and work towards finding a solution.

Thank you for your time and attention to this matter.

Best regards,
Yousuf

**Comment by Xazin** [comment]
Not able to reproduce on Macbook Pro M2 2022 running Ventura 13.3.1
