### ISSUE TITLE
[FR] Disable but still show the AI assistants icon in the toolbar menu when an OpenAI key is not provided 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#1962]
### Description

<img width="486" alt="image" src="https://user-images.githubusercontent.com/12026239/224522283-bb53c920-57e3-4eb7-bf27-9b75dad71834.png">

Allow this feature to be exposed to all the users regardless of the availability of an OpenAI key
When the icon is disabled, give more hints on how to use it in the hover-on tip

### Impact

Users who can benefit from OpenAI services

**Comment by tio-trom** [comment]
Since OpenAI is not Open and it is a profitable company mining data, for which you have to pay to get an API key to use it, I highly suggest to not show this option in the menu. I would even suggest to make this like a 3rd party plugin for appflowy. These "AI" tools are invading us all, and for a cost: both in currency and data collection.

If Appflowy wants to be the clean and open source alternative to Notion where you are in "charge of your data", then it should definitely not promote OpenAI.

I was surprised to see this invasive tool in such a clean and open app like AppFlowy.

**Comment by tio-trom** [comment]
Actually why not use an open source language model https://github.com/nomic-ai/gpt4all ?

**Comment by Xazin** [comment]
> Since OpenAI is not Open and it is a profitable company mining data, for which you have to pay to get an API key to use it, I highly suggest to not show this option in the menu. I would even suggest to make this like a 3rd party plugin for appflowy. These "AI" tools are invading us all, and for a cost: both in currency and data collection.
> 
> If Appflowy wants to be the clean and open source alternative to Notion where you are in "charge of your data", then it should definitely not promote OpenAI.
> 
> I was surprised to see this invasive tool in such a clean and open app like AppFlowy.

Whether to enable OpenAI or not is up to each individual user to decide, thus you're still in control of your data. If you do not want to share anything with OpenAI, then simply use AppFlowy without configuring it.

**Comment by tio-trom** [comment]
Yes but why promote it when we have an open source alternative to openai?
