### ISSUE TITLE
[FR] Show a toast after copying the path

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#2056]
### Description

<img width="458" alt="Screenshot 2023-03-21 at 09 59 26" src="https://user-images.githubusercontent.com/11863087/226502094-0d96952d-339c-4a42-8280-6fea6bd7199d.png">

Show a toast after double tapping to let the users know the path has been copied successfully.

### Impact

Users who copy the data path.

### Additional Context

Please refer to:

* `settings_file_customize_location_view.dart`

**Comment by Sudhanva-Nadiger** [comment]
And tapping doesn't seem appropriate word in desktop mode, isn't it ! 
I suppose, it can be double click!

**Comment by LucasXu0** [comment]
@Sudhanva-Nadiger. What's the difference between double tap and double click in desktop mode?

**Comment by Sudhanva-Nadiger** [comment]
Tapping is in Mobile noe ?

**Comment by BijayKumarPun** [comment]
@Sudhanva-Nadiger @LucasXu0, I'm wondering if a single click would suffice?

**Comment by LucasXu0** [comment]
@BijayKumarPun. I think a single click would cause a misoperation.

**Comment by Sudhanva-Nadiger** [comment]
https://user-images.githubusercontent.com/93595710/227791085-65ebf769-92fb-4b6f-b075-696f1eda18fa.mp4

HI @a-wallen 

### Why this approach is used?
- since the setting UI is a dialog we can't show a snack bar or a toast above it as its already on top of every other widget
- we can show the snack bar on the above level of dialog but before that, it had to be wrapped with a scaffold and make the background transparent which does not allow the closing of dialog on clicking outside of it. more info in this [blog](https://medium.com/@aakashpp/flutter-snack-bar-on-dialog-ea70a3b5e028#:~:text=showSnackBar()%3B%20inside%20the%20alert,behind%20the%20alert%20dialog%20screen.)

###

### how the above implementation is done?
- Wrapped the ListTile with a stateful builder so that the whole widget tree won't rebuild when we set the state
- whenever double tap we show the copied message for a second or so!

if any changes required or can I make a pr for this ?

**Comment by Xazin** [comment]
> HI @a-wallen
> 
> ### Why this approach is used?
> * since the setting UI is a dialog we can't show a snack bar or a toast above it as its already on top of every other widget
> * we can show the snack bar on the above level of dialog but before that, it had to be wrapped with a scaffold and make the background transparent which does not allow the closing of dialog on clicking outside of it. more info in this [blog](https://medium.com/@aakashpp/flutter-snack-bar-on-dialog-ea70a3b5e028#:~:text=showSnackBar()%3B%20inside%20the%20alert,behind%20the%20alert%20dialog%20screen.)
> 
> ### how the above implementation is done?
> * Wrapped the ListTile with a stateful builder so that the whole widget tree won't rebuild when we set the state
> * whenever double tap we show the copied message for a second or so!
> 
> if any changes required or can I make a pr for this ?

I believe the best way to do it, is to have a ScaffoldMessenger inside the Dialog itself, I'll make a commit in a moment showing you what I mean.

**Comment by Sudhanva-Nadiger** [comment]
Heyy ! 
I tried that ! When double tapped I tried to show a scaffold messenger.showSnackbar ! 
It did not work (as in it was appearing below the dialog box)

**Comment by Xazin** [comment]
I just need to fix one minor thing with my setup, it's working as I anticipated.

I will tag you when it's done.

**Comment by Xazin** [comment]
@Sudhanva-Nadiger #2114

**Comment by Sudhanva-Nadiger** [comment]
great!

**Comment by annieappflowy** [comment]
@Sudhanva-Nadiger , is this done?

**Comment by Xazin** [comment]
@annieappflowy my PR for this was merged yes. See #2114

**Comment by a-wallen** [comment]
@annieappflowy please review https://github.com/AppFlowy-IO/AppFlowy/pull/2151 when you get the chance. Its a PR template that will remind contributors to mark their PRs with the `fixes` keyword so that these issues are closed when the PR lands.
