### ISSUE TITLE
[Bug] The Shortcuts option in the help menu is misaligned

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2062]
### Bug Description

<img width="171" alt="image" src="https://user-images.githubusercontent.com/12026239/226540281-31edb7a2-9e3d-4a18-87b7-d3b8dfd6bdae.png">

### How to Reproduce

Click on the `?` icon at the bottom right

### Expected Behavior

It's aligned with other items

### Operating System

MacOS

### AppFlowy Version(s)

release/0.1.1

**Comment by BijayKumarPun** [comment]
Hi @annieappflowy, this looks like a minor issue I can raise a PR for.

Upon investigating further, I found that the root cause is that the keyboard emoji is just too small when compared with other emojis.

Some potential fixes would be:
- To change emoji altogether
- To add a whitespace after the emoji (which will sorta work, but not entirely)

### Screenshots
> Whitespace
<img width="261" alt="hacky" src="https://user-images.githubusercontent.com/13991373/226564979-d25d4502-f5af-49d5-aaf6-29753473195b.png">

> Clipboard Emoji
<img width="261" alt="clipboard" src="https://user-images.githubusercontent.com/13991373/226564958-98cd5141-222c-41ec-963d-ee75f96c2fa6.png">

> Laptop Emoji
<img width="261" alt="laptop" src="https://user-images.githubusercontent.com/13991373/226564992-5f8d8e40-d818-409e-bee0-9e21b9c09f0e.png">


Let me know if any of the above works.

**Comment by a-wallen** [comment]
Adding whitespace will likely cause misalignment on Windows.
![image](https://user-images.githubusercontent.com/44445638/227076027-13b30a78-c484-42f9-9ec1-98060425d5a4.png)

Changing the emoji should be a fine short-term solution. In the long run, we should consider [adding custom icons](https://www.freecodecamp.org/news/how-to-add-custom-icons-to-your-flutter-application/).

@BijayKumarPun I think that changing the emoji to the clipboard should suffice. You can go ahead and submit a PR and request my review.

**Comment by prashant235913** [comment]
@annieappflowy I want to work on this but I am using windows ...Is there any way to test it

**Comment by BijayKumarPun** [comment]
Ok thank you @a-wallen , will raise a PR changing icon to clipboard!
