### ISSUE TITLE
[FR] Create GitHub bot to check whether PRs have tests.

### ISSUE THREAD

**Issue by a-wallen** [AppFlowy-IO/AppFlowy#2084]
### Description

There should be a CI action that checks whether a PR has modified or added files in `test`/`integration_test` directories.

### Impact

Medium.

**Comment by LucasXu0** [comment]
I integrated codecov for checking the code coverage a week ago and closed it later. Because it will almost block all the CI jobs to merge. It will be better to write a document to tell the contributor first. Then reopen it again.

<img width="444" alt="Screenshot 2023-03-23 at 11 30 58" src="https://user-images.githubusercontent.com/11863087/227095000-53bb8a69-d8e5-49e8-acd2-49b55bbdfcd5.png">
