### ISSUE TITLE
[FR] For the icon there can be a name icon used in many apps...so it can create e difference

### ISSUE THREAD

**Issue by prashant235913** [AppFlowy-IO/AppFlowy#2088]
>### Description

from this -
![image](https://user-images.githubusercontent.com/118105825/227150850-2eddcd6d-18a0-4190-a4a3-af4fcb52e1c7.png)
To this -
![image](https://user-images.githubusercontent.com/118105825/227154705-ad408f08-f127-4b00-b63b-57d64191065a.png)

### Impact

User will feel a ownness while using the cool appflowy app...
Maybe it's not a very big contribution ...But something is better than nothing..

**Comment by Xazin** [comment]
Well, it would be relatively easy to implement, and you can generate a random color from the username/name, and let the user pick from a set of colors if they want something custom.

This also means though, there should be an upload avatar feature later on. (Which should come after the Upload Image from Local feature so that there can be some shared abstraction for how image uploads are done)

**Comment by prashant235913** [comment]
True....Its just a start...More features are yet to come...

**Comment by gantanikhilraj** [comment]
I can work on this, assign it to me.

**Comment by prashant235913** [comment]
@gantanikhilraj    Maybe @annieappflowy  can help in this in this

**Comment by annieappflowy** [comment]
@gantanikhilraj , assigned. Thanks for offering the help.

**Comment by nurmukhametdaniyar** [comment]
@annieappflowy Created PR to close this issue. At the moment, there is no Color picker. Color is generated on the name of the user. Then it is checked if it is too light and darkened a bit to make the white text visible.

Looking forward to your review
