### ISSUE TITLE
[Bug] Cmd + k triggers the link dialog when no text is selected

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2233]
### Bug Description

ctrl+k even works if nothing is selected, 

meaning if selection is empty then also a link dialog opens up, where you can add the link, but since no text is selected, the whole operation does nothing. 

We may fix it by only opening up the link menu when and some text is selected.

### How to Reproduce

When the cursor is active, press cmd+k

### Expected Behavior

If text selection is empty, cmd+k doesn't trigger the link dialog

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by rwt-2001** [comment]
I would like to work on this issue.

**Comment by annieappflowy** [comment]
Hi @rwt-2001 , I missed your comment. Are you still keen to work on this issue?

**Comment by Chandan-CV** [comment]
Hi @annieappflowy!
Can I work on this issue?

**Comment by annieappflowy** [comment]
Sure. Assigned it to you, @Chandan-CV

**Comment by Chandan-CV** [comment]
Hi @annieappflowy!
Thank you for assigning me this issue.
I played around a little and figured out the issue is with the appflowy-editor. I took @Xazin's work as a reference, and sent a new PR solving this issue.
[https://github.com/AppFlowy-IO/appflowy-editor/pull/117](url)

I am a beginner in open source and AppFlowy, please correct me if I did something wrong, your guidance is appreciated :rocket: :smile: 

Thank you!

**Comment by Chandan-CV** [comment]
[Screencast from 13-05-23 10:50:23 AM IST.webm](https://github.com/AppFlowy-IO/AppFlowy/assets/37525954/a957b0ae-4e44-408b-b022-0e9b8196b4fb)

**Comment by annieappflowy** [comment]
Fixed. Thanks everyone!
