### ISSUE TITLE
[FR] Support checkbox markdown

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2277]
### Description

As described in the title

### Impact

Users who use markdown to insert a checkbox

**Comment by literalEval** [comment]
@annieappflowy I would like to work on this issue :)

**Comment by annieappflowy** [comment]
Thanks @literalEval for offering the help. Assigned
There might be conflict between `-` to trigger a bulleted list and `- [ ]` to trigger a checkbox.

**Comment by literalEval** [comment]
Noted :)

**Comment by literalEval** [comment]
@annieappflowy just a quick question which I could not find in the contributing docs.
Which branch should I use as a base for changes? `main` or `develop`? Because I see some PRs being merged into `main` too.

**Comment by annieappflowy** [comment]
I suppose `main` should be fine

**Comment by literalEval** [comment]
Thanks :)

**Comment by literalEval** [comment]
@annieappflowy since I am new to this codebase, I am having trouble finding the code that controls this. I looked at [this PR](https://github.com/AppFlowy-IO/AppFlowy/pull/733), but seems like many things have changes since this, as I couldn't find the code that was added in this said PR. Any help will be helpful :)

**Comment by literalEval** [comment]
@annieappflowy I played with AppFlowy manual build a bit and noticed that the checkboxes do work. The only problem is that the unchecked checkbox appears for `- []` instead of `- [ ]` (the space between the brackets).

I looked in the editor code a bit and there seems to be no problem in it. I will look into more depth and let you know.

**Comment by LucasXu0** [comment]
Hey, @literalEval. Because the ` ` (whitespace) is the event that triggers the conversion, I have implemented this logic and assume that this task has been completed.

```dart
const _checkboxListSymbols = ['[x]', '-[x]'];
const _unCheckboxListSymbols = ['[]', '-[]'];
```

**Comment by annieappflowy** [comment]
@literalEval thanks for helping out. I didn't know we supported -[] for the checkbox. I'm closing this issue.

**Comment by literalEval** [comment]
@annieappflowy @LucasXu0 thanks.
Looking forward to solving more issues :)
