### ISSUE TITLE
[Bug] The Select property doesn't work 

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2302]
### Bug Description

<img width="135" alt="image" src="https://user-images.githubusercontent.com/12026239/233325524-1d92ba03-8c54-42e4-b27f-de58e6a3f283.png">

Property 5 is a Select type.
When I click on a cell, it works as a Text type.
When I click on the header, it allows me to enter an option for Property 5
<img width="396" alt="image" src="https://user-images.githubusercontent.com/12026239/233325865-d5ae1be3-5f5c-40b3-8aad-5f5ff72f5610.png">

### How to Reproduce

Add a Select column

### Expected Behavior

When I enter a value, it should ask me to create an option or match with an existing option

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by annieappflowy** [comment]
Cannot reporduce

**Comment by NePoCz** [comment]
Hi, I had a very similar issue - basically the property was not editable at all (can change it in UI, but changes are not reflected, even renaming doesnt work). It was because I started AppFlowy from scratch, selected "Open an existing folder" and then browsed to empty existing folder on PC. Restarting AppFlowy solved the issue, perhaps that is why you were unable to reproduce. My guess would be that choosing empty folder as "existing folder" confuses AppFlowy in some way on first start.

**Comment by annieappflowy** [comment]
Thanks for your input. What operating system did you have when running into this issue?

**Comment by NePoCz** [comment]
I am on Windows 10. The problem was with the installed version from exe, but I think I was also able to reproduce with the portable version as well

**Comment by annieappflowy** [comment]
Ok. Thanks! I will try to reproduce on a Windows and get back to you.

**Comment by annieappflowy** [comment]
Confirmed that I can reproduce the issue on Windows 11 Pro using v0.1.4

**Comment by annieappflowy** [comment]
Should be fixed
Cannot reproduce on Windows 11 using v0.2.1
