### ISSUE TITLE
[FR] Markdown divider implement ***

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2371]
### Description

You can use *** on its own line to add a horizontal bar.

### Impact

Markdown users

**Comment by glunkad** [comment]
Hey @annieappflowy , I would like to work on the task

**Comment by annieappflowy** [comment]
<img width="905" alt="image" src="https://user-images.githubusercontent.com/12026239/235572017-dac74b53-b4fe-4d6f-998d-f18ed926aafd.png">

This feature is implemented. It can only be triggered by `---` though
The task is to support "***" to trigger the horizontal divider.

**Comment by glunkad** [comment]
Hey sorry, I was busy so the issue went inactive. I am bit confuse about where to make changes in appflowy_editor or AppFlowy project?

**Comment by Xazin** [comment]
This is related to #2372 

The divider is currently implemented in AppFlowy, but should be implemented in AppFlowy-Editor.

Either this issue or #2372 should migrate it to the editor, and then add their support for `***` or `___`.

In my opinion it should be one person resolving both the issues, because the logical handler of divider insertion already exists.

What this means, is that the existing solution should just be refactored to take a dynamic character, and then 3 shortcut events should use 3 handlers. `---`, `___`, `***`.

See for reference on how to achieve it: https://github.com/AppFlowy-IO/appflowy-editor/pull/92/files for reference.

**Comment by glunkad** [comment]
Thanks@Xazin , correct me if I'm wrong so the changes are to be made in AppFlowy-Editor project.
