### ISSUE TITLE
[Bug] Filter UI overflow

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2476]
### Bug Description

<img width="426" alt="image" src="https://user-images.githubusercontent.com/12026239/236753711-6937b9d7-aabe-42c7-8520-cef8f12e1c4c.png">

### How to Reproduce

Add two filters to a grid
The second filter filters on a Text column with a long property name

### Expected Behavior

No UI overflow message

### Operating System

MacOS

### AppFlowy Version(s)

v0.1.4

**Comment by Samiksha-Garg** [comment]
Hello! Can I work on this issue?

**Comment by Xazin** [comment]
<img width="682" alt="Screenshot 2023-05-08 at 20 51 23" src="https://user-images.githubusercontent.com/42929161/236920072-529f9836-384f-4dda-9692-dfc64f143f3c.png">

This should already have been resolved, this is on `main`, as seen in the screenshot, actions have been moved above the current applied filters.

**Comment by Samiksha-Garg** [comment]
Hey, @Xazin! I don't think this issue is about filter panel, I feel this is about editing a particular filter with long name. This is the screenshot of editor panel for a long column name on main branch : 
<img width="1117" alt="Screenshot 2023-05-09 at 1 46 11 AM" src="https://user-images.githubusercontent.com/79906086/236925554-9f2c9929-bd26-4a02-a5bc-abfdb785601e.png">
