### ISSUE TITLE
[Bug] Calendar events open up speed

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2498]
### Bug Description

https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/c8aae426-7fe4-4d88-b7b0-225099c09d36

feel a bit sluggish when opening up an event card
not sure if it's just me

### How to Reproduce

Create a calendar
Add an event to a date
Close it
Open it up

### Expected Behavior

Feel smooth and agile?

### Operating System

MacOS

### AppFlowy Version(s)

Main branch

**Comment by richardshiue** [comment]
I can feel it as well

**Comment by Xazin** [comment]
Try in release mode, if you're in dev environment.

**Comment by richardshiue** [comment]
Hey there @Xazin, this is observable in v0.1.5 as well.

I've tracked down the problem to the following:

- There are two `GestureDetector`s in place here, one being the background card that's listening to `onDoubleTap` (to create a new event) and the child event card further down in the widget tree listening to `onTap` (to open the event as a page).
- When a click is detected within the boundary of the child, that event is sent to the gesture arena, where it could be matched for either `onTap` or `onDoubleTap`.
- In order to discern which of the two it is, a 300 ms timer is started to listen for a second tap. Only when it is absolutely sure that the event is not a double tap will the `onTap` handler be called.
- To see this in action, remove the `onDoubleTap` handler and see that clicking on an event card opens the event editing page almost instantaneously.
- Following this logic, there is another bug. If I double-click on the card, a new event will be created. This is unintended behavior as well.

We should make the child perform hit testing immediately, while the parent should ignore hit testing if the child is on top of it. However, I haven't figured out a way to handle the event propagation properly.

- `IgnorePointer` and `AbsorbPointer` are both useless since they block the child, not the parent.
- adding an empty `onDoubleTap` handler to the child `GestureDetector` solves the problem of double tapping on the card creating a new event, but actually opening the event still take a while.

**Comment by MayurSMahajan** [comment]
When I was trying the calendar, I clicked on the event and because it did not open up, I kept clicking it, and the event never opened up as a page, I thought maybe its only my device. 
Can we remove the feature of `double tap to create a new event` **completely** since the plus icon at the top left corner can be used to create a new event ?

**Comment by Xazin** [comment]
> When I was trying the calendar, I clicked on the event and because it did not open up, I kept clicking it, and the event never opened up as a page, I thought maybe its only my device. 
> Can we remove the feature of `double tap to create a new event` **completely** since the plus icon at the top left corner can be used to create a new event ? 
> 

I think this is a good idea.
