### ISSUE TITLE
[Bug] Add a new card

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#2594]
### Bug Description

When the cursor is active, clicking on +New Card only leaves the edit mode but doesn't create a new card

### How to Reproduce

Add a new card
Add a new card again under the same stack

### Expected Behavior

Add a new card should work as intended

### Operating System

MacOS

### AppFlowy Version(s)

Develop

**Comment by vedant-pandey** [comment]
I want to work on this

**Comment by vedant-pandey** [comment]
This issue seems to be coming from [here](https://github.com/AppFlowy-IO/appflowy-board/blob/3a08543f6bd81c782784a23fcd8cc61bfb946f85/lib/src/widgets/board_data.dart#L209-L215) on calling `notifyListeners` -> `markNeedsNotifyDependents` -> `markNeedsBuild` which marks it to be rebuilt and tap is not registered the first time.

**Comment by annieappflowy** [comment]
Assigned to @vedant-pandey 
Thanks for offering the help. If you need guidance, you can ask @richardshiue on Discord

**Comment by annieappflowy** [comment]
Fixed
