### ISSUE TITLE
[FR] consistency edit icon on all pages

### ISSUE THREAD

**Issue by moshe7** [AppFlowy-IO/appflowy#270]
**1~3 main use cases of the proposed feature**
**As a** new user, 
**I want** to see consistency in all the option-setting of items (pages) in the app, for example:
- when creating a page at the main page currently there is a plus icon (+) but the inner page has a dot icon (:), rather than one icon (or two as in notion) identical on all pages.
- plus icon (+) always visible, dot icon (:) only when mouse hover

**So that** I can treat any page intuitively

**what types of users can benefit from using your proposed feature**
mainly new users 

**Additional context**
![image](https://user-images.githubusercontent.com/7399564/151043399-7ee4584a-2571-4d0b-a2e7-9c173aa87b57.png)

**Comment by annieappflowy** [comment]
Thanks for pointing this out. You have a keen eye for detail, which we value a lot. I’ll mark this as an enhancement.

**Comment by Hari-07** [comment]
@moshe7  Doesn't the '+' and ':' have 2 different uses, and seem to be correct imo. The '+' is because we're adding something, if we use '+' in the page wont make sense, since its an edit menu. Whereas if we use ':' to adding the page, it feels less intuitive than the add symbol. Since the utility of the 2 is different, it having different icons seem fine

**Comment by MikeWallaceDev** [comment]
Yep, @Hari-07 is totally right. The icons do different things, and bring up different menus.
