### ISSUE TITLE
[FR] consistency of doc name and doc title without pressing Enter

### ISSUE THREAD

**Issue by moshe7** [AppFlowy-IO/AppFlowy#272]
**1~3 main use cases of the proposed feature**
**As a** user,
**I want** to see consistency between  the name and the header of the doc item
when creating a doc under page, the name of the doc is the same as the title of the doc, but when I update the title, the doc name does not change respectively,
**So that** I can easily update the name of doc the from doc title

**what types of users can benefit from using your proposed feature**
all users

**Additional context**
Before:
![image](https://user-images.githubusercontent.com/7399564/151047858-990d78f0-ea1c-484b-9c1c-f1086c2da537.png)
After: (doesn't changed)
![image](https://user-images.githubusercontent.com/7399564/151047975-ee03ab8d-b927-43f5-a5a8-040ee0c6449c.png)

**Comment by MikeWallaceDev** [comment]
Thank you for you issue report!  I have just tried this and it works.  You have to press Enter for your change to take effect.

![image](https://user-images.githubusercontent.com/5375835/151050898-5d9759a7-c442-4d29-9e60-f6b7f1e3a415.png)


However, I'm leaving this issue for now because I am seeing exceptions while playing with the title.  So please confirm that it does indeed change once you press Enter.  Also, tell me if the app crashes if you play around with the title, and give and remove focus from it (just click in the editor and back onto the title a few times)

**Comment by moshe7** [comment]
Yes, after I pressed Enter the change took effect.
I just expected it to work automatically as in Notion, so the request is a feature and not a bug :)

**Comment by appflowy** [comment]
@moshe7 Do you use the AppFlowy release version? I found there is a bug when I rename it twice in dev mode.

**Comment by moshe7** [comment]
Yap, to test it I used release version.

**Comment by annieappflowy** [comment]
Resolved in v0.0.3
