### ISSUE TITLE
[FR] Persian Language

### ISSUE THREAD

**Issue by TheBinaryParadox** [AppFlowy-IO/AppFlowy#2836]
### Description

Hi,
I want to contribute to this project by translating and add Persian language to it, can I do that? and would you like to add this language to the project?

### Impact

Persian people who don't know English can use the app

**Comment by MayurSMahajan** [comment]
Hey @TheBinaryParadox ! It is great that you want to contribute. Please checkout this page: [Translate AppFlowy](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/translation). Also take a look at the [contributor's guidelines](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/submitting-code).

**Comment by AmirLavasani** [comment]
Is this issue still ongoing? I'd like to help with this issue.

**Comment by MayurSMahajan** [comment]
Hey @TheBinaryParadox, are you still working on this?

**Comment by MayurSMahajan** [comment]
@AmirLavasani you can start working and submit a Pull Request

**Comment by AmirLavasani** [comment]
I hope you are doing well, I have made the translation JSON file for the Persian language. You can check the files in my fork here: https://github.com/AmirLavasani/AppFlowy/tree/feat/persian_lang_2836.

However, I cannot build the project to test the translations. Here is the log for the error. can you check this out?

Here is the command I ran:
`cargo make --profile production-linux-x86_64 appflowy`

The main error line is this:
`[   +1 ms] [+11018 ms] packages/flowy_infra_ui/lib/widget/dialog/styled_dialogs.dart:74:27: Error: The argument type 'BorderRadius?' can't
be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is nullable and 'BorderRadiusGeometry' isn't.`

More of the log:
`[  +67 ms] Building Linux application...
[  +11 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux
[ +132 ms] -- The CXX compiler identification is Clang 10.0.0
[   +2 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++
[ +109 ms] -- Check for working CXX compiler: /snap/flutter/current/usr/bin/clang++ -- works
[        ] -- Detecting CXX compiler ABI info
[  +79 ms] -- Detecting CXX compiler ABI info - done
[   +8 ms] -- Detecting CXX compile features
[        ] -- Detecting CXX compile features - done
[   +4 ms] -- Found PkgConfig: /snap/flutter/current/usr/bin/pkg-config (found version "0.29.1") 
[        ] -- Checking for module 'gtk+-3.0'
[  +17 ms] --   Found gtk+-3.0, version 3.24.20
[  +60 ms] -- Checking for module 'glib-2.0'
[  +12 ms] --   Found glib-2.0, version 2.64.6
[  +33 ms] -- Checking for module 'gio-2.0'
[  +12 ms] --   Found gio-2.0, version 2.64.6
[  +44 ms] -- Checking for module 'keybinder-3.0'
[  +17 ms] --   Found keybinder-3.0, version 0.3.2
[  +67 ms] -- Configuring done
[  +26 ms] -- Generating done
[        ] -- Build files have been written to: /home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/build/linux/x64/release
[   +8 ms] executing: ninja -C build/linux/x64/release install
[   +8 ms] ninja: Entering directory `build/linux/x64/release'
[+21489 ms] [1/19] Generating
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +10 ms] FAILED: /home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/libflutter_linux_gtk.so
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_engine.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_call.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_method_response.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_value.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/fl_view.h
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/linux/flutter/ephemeral/flutter_linux/flutter_linux.h flutter/_phony_
[   +2 ms] cd /home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/build/linux/x64/release/flutter &&
/snap/flutter/141/usr/bin/cmake -E env FLUTTER_ROOT=/home/amir/snap/flutter/common/flutter
PROJECT_DIR=/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter DART_OBFUSCATION=false TRACK_WIDGET_CREATION=true
TREE_SHAKE_ICONS=true PACKAGE_CONFIG=/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/.dart_tool/package_config.json
FLUTTER_TARGET=lib/main.dart /home/amir/snap/flutter/common/flutter/packages/flutter_tools/bin/tool_backend.sh linux-x64 Release
[        ] [  +11 ms] Unable to locate an Android SDK.
[        ] [   +8 ms] executing: uname -m
[        ] [   +2 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [  +17 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +75 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +34 ms] Initializing file store
[        ] [  +14 ms] Skipping target: gen_localizations
[        ] [   +9 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated
contents: /home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/.dart_tool/package_config_subset}
[        ] [   +4 ms] unpack_linux: Starting due to {}
[        ] [  +65 ms] unpack_linux: Complete
[        ] [ +152 ms] Found plugin app_links at /home/amir/.pub-cache/git/app_links-f897e1d81a3d9fcea632588479bc2814d493f7b5/
[        ] [  +22 ms] Found plugin connectivity_plus at /home/amir/.pub-cache/hosted/pub.dev/connectivity_plus-4.0.1/
[        ] [   +4 ms] Found plugin device_info_plus at /home/amir/.pub-cache/hosted/pub.dev/device_info_plus-9.0.1/
[        ] [   +4 ms] Found plugin file_picker at /home/amir/.pub-cache/hosted/pub.dev/file_picker-5.3.1/
[        ] [   +2 ms] Found plugin flutter_plugin_android_lifecycle at
/home/amir/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.15/
[        ] [        ] Found plugin fluttertoast at /home/amir/.pub-cache/hosted/pub.dev/fluttertoast-8.2.2/
[        ] [   +3 ms] Found plugin hotkey_manager at /home/amir/.pub-cache/hosted/pub.dev/hotkey_manager-0.1.7/
[        ] [   +7 ms] Found plugin package_info_plus at /home/amir/.pub-cache/hosted/pub.dev/package_info_plus-4.0.1/
[        ] [   +1 ms] Found plugin path_provider at /home/amir/.pub-cache/hosted/pub.dev/path_provider-2.0.15/
[        ] [        ] Found plugin path_provider_android at /home/amir/.pub-cache/hosted/pub.dev/path_provider_android-2.0.27/
[        ] [        ] Found plugin path_provider_foundation at /home/amir/.pub-cache/hosted/pub.dev/path_provider_foundation-2.2.3/
[        ] [        ] Found plugin path_provider_linux at /home/amir/.pub-cache/hosted/pub.dev/path_provider_linux-2.1.11/
[        ] [        ] Found plugin path_provider_windows at /home/amir/.pub-cache/hosted/pub.dev/path_provider_windows-2.1.6/
[        ] [   +4 ms] Found plugin rich_clipboard at /home/amir/.pub-cache/hosted/pub.dev/rich_clipboard-1.0.1/
[   +2 ms] [        ] Found plugin rich_clipboard_android at /home/amir/.pub-cache/hosted/pub.dev/rich_clipboard_android-1.0.1/
[        ] [        ] Found plugin rich_clipboard_ios at /home/amir/.pub-cache/hosted/pub.dev/rich_clipboard_ios-1.0.0/
[        ] [        ] Found plugin rich_clipboard_linux at /home/amir/.pub-cache/hosted/pub.dev/rich_clipboard_linux-1.0.1/
[        ] [        ] Found plugin rich_clipboard_macos at /home/amir/.pub-cache/hosted/pub.dev/rich_clipboard_macos-1.0.1/
[        ] [        ] Found plugin rich_clipboard_web at /home/amir/.pub-cache/hosted/pub.dev/rich_clipboard_web-1.0.2/
[        ] [        ] Found plugin rich_clipboard_windows at /home/amir/.pub-cache/hosted/pub.dev/rich_clipboard_windows-1.0.2/
[        ] [   +2 ms] Found plugin screen_retriever at /home/amir/.pub-cache/hosted/pub.dev/screen_retriever-0.1.6/
[        ] [   +1 ms] Found plugin shared_preferences at /home/amir/.pub-cache/hosted/pub.dev/shared_preferences-2.1.1/
[        ] [        ] Found plugin shared_preferences_android at /home/amir/.pub-cache/hosted/pub.dev/shared_preferences_android-2.1.4/
[        ] [        ] Found plugin shared_preferences_foundation at
/home/amir/.pub-cache/hosted/pub.dev/shared_preferences_foundation-2.2.2/
[        ] [        ] Found plugin shared_preferences_linux at /home/amir/.pub-cache/hosted/pub.dev/shared_preferences_linux-2.2.0/
[        ] [   +2 ms] Found plugin shared_preferences_web at /home/amir/.pub-cache/hosted/pub.dev/shared_preferences_web-2.1.0/
[        ] [        ] Found plugin shared_preferences_windows at /home/amir/.pub-cache/hosted/pub.dev/shared_preferences_windows-2.2.0/
[        ] [   +1 ms] Found plugin sign_in_with_apple at /home/amir/.pub-cache/hosted/pub.dev/sign_in_with_apple-4.3.0/
[        ] [        ] Found plugin sign_in_with_apple_web at /home/amir/.pub-cache/hosted/pub.dev/sign_in_with_apple_web-1.0.1/
[        ] [  +17 ms] Found plugin url_launcher at /home/amir/.pub-cache/hosted/pub.dev/url_launcher-6.1.11/
[        ] [        ] Found plugin url_launcher_android at /home/amir/.pub-cache/hosted/pub.dev/url_launcher_android-6.0.34/
[        ] [        ] Found plugin url_launcher_ios at /home/amir/.pub-cache/hosted/pub.dev/url_launcher_ios-6.1.4/
[        ] [        ] Found plugin url_launcher_linux at /home/amir/.pub-cache/hosted/pub.dev/url_launcher_linux-3.0.5/
[        ] [        ] Found plugin url_launcher_macos at /home/amir/.pub-cache/hosted/pub.dev/url_launcher_macos-3.0.5/
[        ] [   +1 ms] Found plugin url_launcher_web at /home/amir/.pub-cache/hosted/pub.dev/url_launcher_web-2.0.17/
[        ] [        ] Found plugin url_launcher_windows at /home/amir/.pub-cache/hosted/pub.dev/url_launcher_windows-3.0.6/
[        ] [   +5 ms] Found plugin webview_flutter at /home/amir/.pub-cache/hosted/pub.dev/webview_flutter-4.2.1/
[        ] [        ] Found plugin webview_flutter_android at /home/amir/.pub-cache/hosted/pub.dev/webview_flutter_android-3.7.1/
[        ] [        ] Found plugin webview_flutter_wkwebview at /home/amir/.pub-cache/hosted/pub.dev/webview_flutter_wkwebview-3.4.4/
[        ] [   +1 ms] Found plugin window_manager at /home/amir/.pub-cache/hosted/pub.dev/window_manager-0.3.4/
[        ] [   +3 ms] Found plugin appflowy_backend at
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/packages/appflowy_backend/
[        ] [   +1 ms] Found plugin flowy_infra_ui at
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/packages/flowy_infra_ui/
[        ] [        ] Found plugin flowy_infra_ui_web at
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/packages/flowy_infra_ui/flowy_infra_ui_web/
[   +1 ms] [   +4 ms] Found plugin integration_test at /home/amir/snap/flutter/common/flutter/packages/integration_test/
[        ] [  +14 ms] gen_dart_plugin_registrant: Complete
[        ] [        ] kernel_snapshot: Starting due to {}
[   +2 ms] [   +8 ms] /home/amir/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/amir/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/amir/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter
--no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --target-os linux --packages
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/.dart_tool/package_config.json --output-dill
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/.dart_tool/flutter_build/8a507e605ba3f73fec5569230ed0d6be/app.dill
--depfile
/home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/.dart_tool/flutter_build/8a507e605ba3f73fec5569230ed0d6be/kernel_snapsh
ot.d --source
file:///home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/.dart_tool/flutter_build/dart_plugin_registrant.dart --source
package:flutter/src/dart_plugin_registrant.dart
-Dflutter.dart_plugin_registrant=file:///home/amir/projects/personal/code/AppFlowy/frontend/appflowy_flutter/.dart_tool/flutter_build/dart_p
lugin_registrant.dart --verbosity=error package:appflowy/main.dart
[   +1 ms] [+11018 ms] packages/flowy_infra_ui/lib/widget/dialog/styled_dialogs.dart:74:27: Error: The argument type 'BorderRadius?' can't
be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is nullable and 'BorderRadiusGeometry' isn't.
[   +1 ms] [   +1 ms]  - 'BorderRadius' is from 'package:flutter/src/painting/border_radius.dart'
('../../../../../../snap/flutter/common/flutter/packages/flutter/lib/src/painting/border_radius.dart').
[        ] [        ]  - 'BorderRadiusGeometry' is from 'package:flutter/src/painting/border_radius.dart'
('../../../../../../snap/flutter/common/flutter/packages/flutter/lib/src/painting/border_radius.dart').
[        ] [        ]             borderRadius: borderRadius,
[        ] [        ]                           ^
[        ] [+9369 ms] Persisting file store
[        ] [   +1 ms] Done persisting file store
[        ] [   +1 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:256:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
[        ]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
[        ]            <asynchronous suspension>
[        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
[        ]            <asynchronous suspension>
[        ]            #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)
[   +1 ms]            <asynchronous suspension>
[        ]            #8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)
[        ]            <asynchronous suspension>
[        ]            #9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:315:32)
[        ]            <asynchronous suspension>
[        ]            #10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
[        ]            <asynchronous suspension>
[        ]            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
[        ]            <asynchronous suspension>
[        ]            #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
[        ]            <asynchronous suspension>
[        ]            #16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
[        ]            <asynchronous suspension>
[        ]            #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #18     main (package:flutter_tools/executable.dart:90:3)
[        ]            <asynchronous suspension>
[        ] [   +6 ms] "flutter assemble" took 20,896ms.
[        ] [   +2 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:332:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:90:3)
[        ]            <asynchronous suspension>
[        ] [ +256 ms] ensureAnalyticsSent: 251ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] ninja: build stopped: subcommand failed.
[  +11 ms] Building Linux application... (completed in 22.2s)
[        ] "flutter linux" took 22,825ms.
[   +5 ms] Build process failed
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:181:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:75:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:86:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +253 ms] ensureAnalyticsSent: 250ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
[cargo-make][1] ERROR - Error while executing command, exit code: 1
[cargo-make][1] WARN - Build Failed.
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: restore-crate-type
[cargo-make] ERROR - Task error detected, exit code: 1
[cargo-make] WARN - Build Failed.`

**Comment by MayurSMahajan** [comment]
hey @AmirLavasani, can you try [Running the application without building (using VS Code)](https://docs.appflowy.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-linux#miscellaneous-running-the-application-without-building-using-vs-code)

cc: @richardshiue, @rileyhawk1417 
shouldn't developers run `cargo make --profile development-linux-x86_64 appflowy-dev ` 
instead of `cargo make --profile production-linux-x86_64 appflowy` 
on our docs, we are showing building release binary first and debug binary is hidden.

**Comment by richardshiue** [comment]
Hi @AmirLavasani, the PR looks good to me. Our application is currently being built against flutter 3.10.1. Based on your logs, I'm guessing that you installed flutter from snapcraft which is using the latest version. That package includes this [commit](https://github.com/flutter/flutter/commit/4bf297ceb23c7c287fb626ab58893d6787be603a) which makes our code incompatible. If you'd like to test, please downgrade your flutter version.

**Comment by AmirLavasani** [comment]
Alright, I'll create the PR. 

I tested and the error was due to the flutter version. Thanks for the help :pray:
