### ISSUE TITLE
Markdow export

### ISSUE THREAD

**Issue by Cavalletta98** [AppFlowy-IO/AppFlowy#3055]
Hi, when i try to export a document,as Markdown, with inside some code snippets, the code parts will note be exported. Why?

**Comment by Mukund-Tandon** [comment]
I would like to work on this issue 
I have found the bug
Current Progress-
Before -

https://github.com/AppFlowy-IO/AppFlowy/assets/71614009/77ab0d75-94ba-427e-965c-d2359cb82aa4

After-

https://github.com/AppFlowy-IO/AppFlowy/assets/71614009/9cfa4ed1-5b8a-4494-bb11-721b17470995


Currently it is not exporting the language of the code( dart in the above video example ),will fix that also

**Comment by Cavalletta98** [comment]
Great!!. I saw the same problem for the images. I don't know if could be fixed also this

**Comment by Mukund-Tandon** [comment]
> Great!!. I saw the same problem for the images. I don't know if could be fixed also this

Ok👍, will look into images also .

**Comment by julian-i** [comment]
# Current progress


### Main List
---
> Communication preferences at quote are not required it seems (issue?). - Do users have to opt into any technically? 

Spoke to Abdi, the issue is there is no validation on the can we call you question

 - [x] Checked and is now working
---
> 
Where did you hear about us field is not required during the annual insurance. - Currently not validated, is this required? Is validated in Bentley and other brands, needs validation. 
- [x] Checked this again and is now working, when I don't select a communication option (can we call you), it brings up the validation error
---
> When adding an extreme amount of characters when adding a address manually, you get caught in a loop when trying to progress. There should be a validation here too. 
- [x] After speaking to Toby we agreed a sensible max length for the address fields should be 60 unless postcode which is 8. Updated the input validation, Need to look at backend / validation
---
> _There is the issue of putting symbols and many characters in the email and phone field which leads to the technical difficulties page, this should have a validation_ 

I'm able to put the symbols in but it doesn't show an error. For the email it could technically be a correct email address (i.e. <><>!!!???@gmail.com is technically a correct email) even though it's just a bunch of symbols. 
I've looked at the validation code and it's checking that there is a value and uses a regular expression to confirm that it is an email format 
- [x] Check email validation - Checked and is sufficent, may need more of a conversaion around this but I think it's suitable
- [x] Check phone validation - The phone number validator is only checking if there is a value although the input field has a max length of 15 characters. I do notice however we do check the phone number with a regex but only on the server side. I've implemented the same regex on client side so although you can put symbols and whitespaces into phone number, it will show a client side error when you try to progress
---
> I'm able to enter whitespaces into the phone number field and it does not give me an error, instead throwing me back to policy start date section when trying to progress. - 

Same as above I can enter the whitespace but it doesn't throw an error and lets me progress 
- [x] need to look at telephone futher
---
> There is an error that when adding an additional driver, entering their occupation in the form prevents you from progressing. - 

Was able to recreate, shows a validtion error, also behaves oddly when removing a driver and going back to add another.
- [ ] Confirmed the behavor, have assesed the data that it's passing through and there a few spots it's failing the validation - currently looking into them 

> Claims and convictions forms do not disappear when going from yes to no unless cancelled. Then you have to reselect the no options - 

This will require changing the logic around claims and convictions, are we happy that we want to do this? 
- [ ] Assess how big this is / Speak to Adrian
---



### Other Changes
- [x] Change color to offwhite for form 
- [x] Inconsistant spacing on DOB (additional driver) - Can be fixed by removing padding right on first dropdown and adding flex with a gap to the parent
- [x] Change background color on inputs/dropdowns
- [x] Align menu button
- [x] Padding required under Where did you hear about us - not required after color change
- [x] Other boxes not showing for car overnight location
- [x] Padding offset is larger on the top
- [x] Menu button doesn't look right (session timout page)
- [ ] Double check autofil styles 
- [ ] If you click the confirm button before the continue button has appeared, you cannot continue unless you untick the confirm button
- [ ] Put the spinner in the button to prevent it colapsing?
