### ISSUE TITLE
[Bug] Handling of the currency Euro

### ISSUE THREAD

**Issue by improve-code** [AppFlowy-IO/AppFlowy#3096]
### Bug Description

I have a grid with a column formated as Euro (€):

> If I enter ,,100" then ,,€100" is shown. (correct)
> If I enter ,,1000" then ,,€1,00" is shown. (wrong)
> If I enter ,,1000000" then ,,€1,00" is shown. (wrong)

> If I enter ,,5,00" then ,,€500" is shown. (wrong, using "," as decimal seperator)
> 
> If I enter ,,5.00" then ,,€500" is shown. (also unexpected).

Additional Problem: 
If I sort by the column Text ,,€1,00" is handeld as beeing of value €100 in the sorting. To get shown ,,€1,00" I entered ,,1000" or ,,1000000" (see above).

Additional Info:
1 euro (€) = 100 euro cent
Common notation: 1 euro (€) = 1,00 euro (€) = 100 euro cent

### How to Reproduce

1) Create a new grid.
2) Click ,,+ New property"
3) Select ,,Numbers"
4) Select Euro as number format
5) Enter the mentioned values

### Expected Behavior

For the right conversion see above.

### Operating System

Linux

### AppFlowy Version(s)

0.2.7

**Comment by annieappflowy** [comment]
5,00 should be 5.00

v0.2.9 still reads 5,00 as 500, can't read 10.000 correctly

**Comment by annieappflowy** [comment]
Not sure I understand the Euro currency format fully though

**Comment by Xazin** [comment]
The common in Europe is comma for decimals and dots for thousand separators.

So `5,00` is correct, and not `5.00`, because that would have to be `5.000,00` as in five-thousand.

I'll take a look and resolve it, but just to say before I do, that the above will be the result, let me know if there is any disagreement :joy:

**Comment by improve-code** [comment]
To clarify:

1.
I would use a dot (.) only, if there are exactly three numbers behind the dot 
(three numbers following the dot, not separated by a comma).

> e.g. 1.000 € (one thousand), 1.500 € (one thousand five hundred)

2.
The dot (.) can be combined with a comma (,).

> e.g. 1.200,50 € (one thousand two hundred euros and fifty (euro-)cents)

3.
There can be multiple dots (.), each before three numbers following.

> e.g. 1.000.000 € (one million)

4.
Instead of dots you can also use a space ( ), in my opinion.

> e.g. ,,1 000 000 €" = ,,1.000.000 €" (one million)

5.
In my opinion dot is not necessary to give a correct number.


If there exist other conventions, I don't know them.

**Comment by annieappflowy** [comment]
<img width="145" alt="image" src="https://github.com/AppFlowy-IO/AppFlowy/assets/12026239/3eb3692b-3893-4bca-a024-5979eaf0b13f">
Ok, so except for €500, everything else follows @improve-code 's suggestions.
I consider this issue was resolved.
Please open a new issue if there's anything we could improve regarding the Euro formats.
