### ISSUE TITLE
[Bug] Slash Menu Overlay Clipped When Screen is Small

### ISSUE THREAD

**Issue by a-wallen** [AppFlowy-IO/AppFlowy#3218]
### Bug Description

I don't know exactly how to reproduce, but the slash menu is clipped for some reason when the screen is small.

### How to Reproduce

Make the app as small as possible and trigger the slash menu.

### Expected Behavior

The slash menu is shown in full

### Operating System

Windows 10

### AppFlowy Version(s)

main

**Comment by a-wallen** [comment]
related to https://github.com/AppFlowy-IO/AppFlowy/issues/1329

**Comment by Xazin** [comment]
I know this isn't the proper solution, but currently we have a max amount of items per column (5 I believe), this is extremely bad when you have too many items, as the slash menu becomes wider.

I was thinking we should implement an option, to dynamically allocate columns based on available size for the slash menu, as well as items.

This means that at the lowest possible width, the slash menu would be a one-column scrollable view. Since we have keyword search, I think it's valuable also for projects using the editor. If there is space for 2 columns, then it would distribute items equally amongst the two rows.

What do you think about this concept? I believe we have fixed width for an item, so we know the minimum size needed per column in the slash menu, and can thus calculate it on-demnad.
