### ISSUE TITLE
[Bug] Tabs overlap with macOS window controls

### ISSUE THREAD

**Issue by intonarumori** [AppFlowy-IO/AppFlowy#3316]
### Bug Description

Tabs overlap with macOS window controls when the sidebar is closed.

### How to Reproduce

- Open multiple windows
- Close sidebar

### Expected Behavior

The tabs and window controls don't overlap.

### Operating System

macOS Ventura 13.2.1

### AppFlowy Version(s)

Version 0.3.0 (0.3.0)

### Screenshots

<img width="409" alt="Screenshot 2023-09-01 at 14 35 24" src="https://github.com/AppFlowy-IO/AppFlowy/assets/86030/8b0fcef2-e0ac-4a1a-8e07-5184c3cdc4f9">

**Comment by MayurSMahajan** [comment]
Thanks for reporting @intonarumori!

**Comment by MayurSMahajan** [comment]
cc @Xazin

**Comment by Xazin** [comment]
Good catch

**Comment by vincendep** [comment]
Hi, I was taking a look at this and I managed to easily add a left padding to the tab bar, as already done for the top bar.
![Screenshot 2023-09-12 alle 16 00 19](https://github.com/AppFlowy-IO/AppFlowy/assets/37916223/c985b529-bf80-4af4-9604-26f462d84da5)
But I am not sure about the final visual result, and I also noticed that the tab bar lacks of two main functionalities:
1. Tabs reordering
2. Window movements detection

Particularly, the lack of the second one feels a bit weird to me, since the top bar underneath the tab bar has such functionality. The easiest solution that come to my mind is to move the tab bar under the top bar.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/37916223/0e22306d-2f04-464e-88ca-bf7cea511ff1)
![Screenshot 2023-09-12 alle 16 28 19](https://github.com/AppFlowy-IO/AppFlowy/assets/37916223/835cd97e-cb61-4132-904b-f47c775c6290)
In this way, the lacks of windows movements detection on the tab bar would reasonable, and tabs reordering could be implemented without such complications.

**Comment by Xazin** [comment]
> Hi, I was taking a look at this and I managed to easily add a left padding to the tab bar, as already done for the top bar. ![Screenshot 2023-09-12 alle 16 00 19](https://user-images.githubusercontent.com/37916223/267360038-c985b529-bf80-4af4-9604-26f462d84da5.png) But I am not sure about the final visual result, and I also noticed that the tab bar lacks of two main functionalities:
> 
> 1. Tabs reordering
> 2. Window movements detection
> 
> Particularly, the lack of the second one feels a bit weird to me, since the top bar underneath the tab bar has such functionality. The easiest solution that come to my mind is to move the tab bar under the top bar. ![image](https://user-images.githubusercontent.com/37916223/267363176-0e22306d-2f04-464e-88ca-bf7cea511ff1.png) In this way, the lacks of windows movements detection on the tab bar would reasonable, and tabs reordering could be implemented without such complications.

Actually, we are in the midst of completely removing the need for the "top bar", see https://github.com/AppFlowy-IO/appflowy-editor/pull/392

After this, we will add the functionality to AppFlowy, and of course we should make the change for the padding so the buttons don't overlap with the tabbar, and also make the non-tabs part of the tab bar detect window movements. I will include this functionally as part of this :+1:
