### ISSUE TITLE
[Bug] Can't copy or cut anything from text area

### ISSUE THREAD

**Issue by Twilightssuperb** [AppFlowy-IO/AppFlowy#342]
AppFlowy 0.0.3-beta2, Win 8.1 x64

Make note.
Type something at text area.
Select it.
Try to launch context menu for selection.
Get nothing.
Try to press Ctrl+X or Ctrl+C.
Open notepad/text processor or clipboard manager.
Get nothing was copied from AppFlowy.

**Comment by apomalyn** [comment]
**Describe the bug**
Impossible to copy or cut from the Doc editor. 

**To Reproduce**
Steps to reproduce the behavior:
1. Go to any Doc page
2. Type anything
3. Select it or double-click on it
4. Try to open the context menu OR try [Ctrl | Command] + C OR try [Ctrl | Command]  + X
5. See the error

**Expected behavior**

I should be able to copy and cut from the editor.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version: 0.0.4.1

**Additional context**

If you are on a grid page everything is working as expected.
