### ISSUE TITLE
[FR] Add missing Amharic translation for AppFlowy

### ISSUE THREAD

**Issue by nebiyuelias1** [AppFlowy-IO/AppFlowy#3728]
### Description

Add a translation for the Amharic language for the app so that users from Ethiopia can use the app in their own language.

### Impact

It means the user base for the app could potentially grow.

**Comment by MayurSMahajan** [comment]
Hey @nebiyuelias1! Review old PRs related to Translations to get hints for your work.

**Comment by nebiyuelias1** [comment]
@MayurSMahajan thank you very much. But I noticed the json file for the Amharic language with code (et-am) doesn't exist. Am I supposed to create it myself manually?

**Comment by MayurSMahajan** [comment]
Yes, since this language doesn't exist in AppFlowy, you should follow guidelines in our documentation for adding new language. I would also recommend you checkout the recently merged PR which added Hindi Language. 

As an exercise I leave it upto you to find these resources on your own. But let me know if you can't find them.

**Comment by nebiyuelias1** [comment]
@MayurSMahajan I'm closing this issue as the PR has been merged.

**Comment by nebiyuelias1** [comment]
@MayurSMahajan But I wonder why your pipeline is failing?

**Comment by MayurSMahajan** [comment]
Thanks for contributing and adding a new language to AppFlowy! The pipeline issue is something that the team is trying to solve. Don't worry about it, keep on contributing.
