### ISSUE TITLE
[FR] Ability to select monospaced fonts for code blocks

### ISSUE THREAD

**Issue by rinodrops** [AppFlowy-IO/AppFlowy#3915]
### Description

Some users, including me, want to use monospaced fonts for code (even if I'm a C++ programmer ;)). 
Considering arguments related to the programming fonts took various places on the net, it is preferable to choose the font from locally installed on the PC: #3534

### Impact

Everyone who dances with the best coding font of the year.

**Comment by halr9000** [comment]
Monospace should always be the default for code blocks IMHO. I can hardly think of a situation where a proportional font would be preferred unless someone were "misusing" it as a shortcut to bring emphasis to an arbitrary block of text.

Which arguably, you guys do right here lol, but that's ok, I forgive you because you've got a sweet app.
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/18482/22270552-c1b0-461c-b1bd-6eac56e43f34)

"however" - arbitrary choice IMHO
"/", "/bullet", "/num": these do make sense as they are string literals
"Document", "Grid", "Kanban Board" are iffy to me. Proper nouns to be sure, so capitalized. But not sure if I would use code block for emphasis this way.

I'm being picky about this calling back to my time as author of [a tech book](https://www.google.com/books/edition/Managing_Vmware_Infrastructure_with_Wind/2HpvPgAACAAJ?hl=en) with lots of code samples, and experience working with docs teams at my employer.

**Comment by annieappflowy** [comment]
@rinodrops @halr9000 
We have added monospaced fonts for code blocks in the latest release ([v0.5.5](https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.5.5))
Please give it a try and let us know your feedback.
