### ISSUE TITLE
[Bug] Installer is flagged by Windows Defender and Virus Total

### ISSUE THREAD

**Issue by 8sd** [AppFlowy-IO/AppFlowy#4053]
### Bug Description

Hi there, 
I'm new to AppFlowy. I tried to install the program on my PC today, but Windows Defender blocked the execution. To double-check for security, I uploaded the file to [VirusTotal](https://www.virustotal.com/gui/file/00b60c91e7c65abca0115f3b19256f9fe02d1ed7601a5fdca0c8e006de6cfb3d), and it was flagged as malicious.
It would be beneficial for the acceptance of AppFlowy if both security systems would flag the installer (I will wait until then to install it).
Thank you for the excellent project!

### How to Reproduce

Execute the installer on windows with Defender running and upload the installer to VirusTotal.

### Expected Behavior

No flags

### Operating System

WIN

### AppFlowy Version(s)

0.3.8

### Screenshots

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/32878822/b44ffa4c-76b2-4f44-85e1-d400219bd650)

**Comment by Xazin** [comment]
Windows defender only complains about the application being unrecognised.

This is because we do not currently have Windows Store setup with an official developer profile.

I guarantee you, if you download AppFlowy from the right source, which is from here on our GitHub Release page, or our official website, there is nothing to worry about.

When you use tools like VirusTotal, it looks for certain actions, such as moving, downloading, and generally unpacking files. This often causes false positives.

The providers that actually complain, are not the antivirus providers you would actually use.

If Windows Defender thought it was truly a malicious source, it would have removed the file on download, and if you use Chrome, it would have stopped you from downloading it.
