### ISSUE TITLE
[FR] OpenAi image pull

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#4315]
### Description

eah, but i am completely fine with paying for it myself. I get free cloud sync and an open source software, thats more i get than by using notion (and it works offline!). I just want to know if i am able to use openai with a limit of 5 img/min while appflowy requests 6 at once haha

### Impact

how can we enable everyone gets to try this feature

**Comment by TheItsNameless** [comment]
More Context:

When starting a new account on OpenAI and charging it with 5$, you only get 5 img/min rate limit, which is not enough for appflowy, as it automatically requests 6 at once. To get to a higher tier, you need to charge 50$ and have at least 7 days since your first payment, which might take a while to reach for an average user.

https://platform.openai.com/docs/guides/rate-limits/usage-tiers

**Comment by davystrong** [comment]
Also running into this issue. Is it just a question of changing the value in `frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/open_ai_image_widget.dart`? Or is there some reason for choosing 6?

**Comment by suntorytimed** [comment]
@TheItsNameless is it really enough to charge? For me, it shows I also have to use those 50 USD and not only charge my account. Which takes even longer.
