### ISSUE TITLE
[Bug] Mac app asking to "Create a new work area"

### ISSUE THREAD

**Issue by mizzyc** [AppFlowy-IO/AppFlowy#482]
I just downloaded the release 0.0.4_beta.3, and got this bug:
<img width="912" alt="Captura de Tela 2022-05-04 às 11 16 45" src="https://user-images.githubusercontent.com/94845181/166701028-6e64a295-a680-4e0d-afd7-06c174efbbfe.png">

Nothing happens when I click the button and I can't do nothing with the app.
Same is happening with release 0.0.3.

**Comment by mizzyc** [comment]
Updating: I downloaded the release 0.0.2 and it works fine. But still can't use the newest version :(

**Comment by mizzyc** [comment]
@appflowy @annieappflowy 
Just to updated: I tried the new release 0.0.4 and I'm still having the same error :( 
Is there anything I can do? I really wanna try the new database feature!

**Comment by appflowy** [comment]
@mizzyc It seems like there are two bugs here: 
1. The left menu of AppFlowy is collapsed because the window's size is too small. AppFlowy should show the uncollapse button on the top bar menu.

solution:
You can try to expand the window size to check out the left menu is shown or not

2. Just like the error message describes: some internal errors happened.
You can DM me in discord if you want to solve this.

**Comment by mizzyc** [comment]
Hey @appflowy, thanks for your help! 
I tried really hard to solve it yesterday and just found a solution:
I've searched my Mac for every file called "flowy" and deleted them. After that, I can open the app normally.
It looks like it's something related to files from older versions!

**Comment by appflowy** [comment]
> Hey @appflowy, thanks for your help! I tried really hard to solve it yesterday and just found a solution: I've searched my Mac for every file called "flowy" and deleted them. After that, I can open the app normally. It looks like it's something related to files from older versions!


Thank you for trying! Actually, I want to find out how that happened. Anyway, If you still have questions, feel free to ask.😁
