### ISSUE TITLE
[Bug] Icon not moving to newly selected item in date/time format, select colors, etc.

### ISSUE THREAD

**Issue by dadyarri** [AppFlowy-IO/AppFlowy#545]
**Describe the bug**
When selected element is changed, check icon don't moves to this element, though selection is working

**To Reproduce**
1. Go to Date & Time format
2. Click on any item
3. While format changing, icon doesn't move to new selection

**Expected behavior**
Icon should move to newly selected item

**Video**

https://user-images.githubusercontent.com/51821039/172632401-bd644fae-cd25-49f6-b51e-79aa35c77ada.mp4

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Version 0.0.4

**Comment by richardshiue** [comment]
This issue is no longer present in the latest version:

- for select option colors when editing from the cell, the selected color instantly updates
- for select option colors when editing from the field header, the popover closes when the user selects a color
- for date format, the popover closes when the user selects a specific format 

Closing as completed!
