### ISSUE TITLE
[Bug] New cards cannot be dragged

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#5525]
### Bug Description

When creating a new card, there are sometimes when it can't be dragged.

### How to Reproduce

See video

### Expected Behavior

Can drag cards

### Operating System

Windows

### AppFlowy Version(s)

0.5.8

### Screenshots

https://github.com/AppFlowy-IO/AppFlowy/assets/42929161/83d2cdec-6350-41fa-a21c-094dbbfc6fbc

**Comment by LinuxLowell** [comment]
I am also experiencing this problem but on MacOS (Ventura), i9 based MacBook Pro. I’m using AppFlowy Version 0.6.7 (2). 

Here’s what I am seeing. When I create a new card and drag it to a new column or drag an existing card to a new column, it sometimes behaves like I am trying to drag the whole column instead of just the card. right now it seems to be just one column, the column I create most of my cards in. Perhaps it is related to number of cards created in a specific column?

Originally I thought it was related to special characters in the card name. The first time it happened the card name was something like “Meet w/ Fred”. I changed it to “Meet with Fred” and the behavior returned to normal.

**Comment by annieappflowy** [comment]
leave the page and reopen would solve the issue
This bug is also on macOS. Not sure about Linux
