### ISSUE TITLE
[Bug] wrong download link in winget's repo 

### ISSUE THREAD

**Issue by orkeilius** [AppFlowy-IO/AppFlowy#5604]
### Bug Description

Wrong download link for 0.6.1
(there is a "v" in the version that shouldn't be here)
https://github.com/AppFlowy-IO/AppFlowy/releases/download/v0.6.1/AppFlowy-0.6.1-windows-x86_64.exe

### How to Reproduce

install/update appflowy with winget

### Expected Behavior

the link should be

https://github.com/AppFlowy-IO/AppFlowy/releases/download/0.6.1/AppFlowy-0.6.1-windows-x86_64.exe

### Operating System

windows

### AppFlowy Version(s)

0.6.1

**Comment by orkeilius** [comment]
Issue in the winget repos : https://github.com/microsoft/winget-pkgs/issues/159413

**Comment by Dragon1573** [comment]
@AppFlowy-IO - Since the package is released directly on **GitHub Releases**, would you consider take full control of your package manifests on [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs/tree/master/manifests/a/AppFlowy/AppFlowy), with automatically submitting manifests with [WinGet Releaser v2](https://github.com/marketplace/actions/winget-releaser)? This can keep manifests always up to date once a new version is released. 🙏🏼

**Comment by LucasXu0** [comment]
@Dragon1573 the version was correctted a few day ago. 

> AppFlowy-IO - Since the package is released directly on GitHub Releases, would you consider take full control of your package manifests on microsoft/winget-pkgs, with automatically submitting manifests with WinGet Releaser v2?

Sure, we can integrate the WinGet Releaser into our CI release job.

**Comment by orkeilius** [comment]
Fixed and closed in winget's repo
