### ISSUE TITLE
[Bug] The Application does not open on android

### ISSUE THREAD

**Issue by Jennifer2005x** [AppFlowy-IO/AppFlowy#5616]
### Bug Description

When I try to open the application the screen is blank for a few seconds and then I return to the start screen

### How to Reproduce

1. Open the app
2. Bug

### Expected Behavior

That the app will let me access so I can enjoy it

### Operating System

Android 10 - Samsung

### AppFlowy Version(s)

0.6.1

**Comment by emmggi** [comment]
Same issue with Android 9 with a few previous versions. Which apk did you use?

**Comment by Jennifer2005x** [comment]
> Same issue with Android 9 with a few previous versions. Which apk did you use?

The one of my architecture, armv7

**Comment by emmggi** [comment]
> The one of my architecture, armv7

Yeah v7a apk, same.

**Comment by LucasXu0** [comment]
<img width="1015" alt="Screenshot 2024-07-10 at 10 34 47" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/a4ac6b8a-948a-4e32-aa43-5459a887dcfe">

https://github.com/flutter/flutter/issues/83596#issuecomment-2198044794

It's a compatibility issue since we upgraded to Flutter 3.22, I'm looking for a workaround.

**Comment by 09u2h4n** [comment]
This problem still exist.
I'm using Huawei y6p, it is Android 10 and when i click the app it doesn't works, suddenly closing.

**Comment by annieappflowy** [comment]
Require Android 10 or above; 
ARMv7 is not supported
