### ISSUE TITLE
[Bug] Mac OS error 50 on uploading files

### ISSUE THREAD

**Issue by SA-al-000** [AppFlowy-IO/AppFlowy#6796]
### Bug Description

on opening the file uploaded  from documents the message display says   Mac error 50 

### How to Reproduce

Not sure

### Expected Behavior

Not sure

### Operating System

Mac OS Sequoia  15.1

### AppFlowy Version(s)

0.7.3 for Mac

### Screenshots

<img width="1512" alt="Screenshot 2024-11-14 at 9 29 27 PM" src="https://github.com/user-attachments/assets/ed9efcea-e084-4815-92d5-8ecfbb75946b">

**Comment by LucasXu0** [comment]
@Xazin For local mode, should we disable the file upload menu or redirect links to local paths?

**Comment by SA-al-000** [comment]
This error occurs even in the Appflowy Cloud mode.

**Comment by Xazin** [comment]
It is trying to open the file on your local, but the default application for opening files with that extension, is failing to open the file for some reason. That can be permission related, file corruption, etc.

Can you open the file normally by double clicking on it?

Is the file in external storage? Or is AppFlowy located in external storage?

Is this computer a school/work computer, is there other anti-virus applications installed?

For reference, this error should be caused by your system and not AppFlowy.

**Comment by Xazin** [comment]
> @Xazin For local mode, should we disable the file upload menu or redirect links to local paths?

We handle files same as images, we store a copy in a known location when in local mode.

This error shouldn't be related to our implementation.

**Comment by SA-al-000** [comment]
1. The files are opening normally by double clicking it.
2. The files and Appyflow are on the Mac.
3. This is a personal computer with no anti virus applications installed.
4. I ran the disk utility to repair any disk problems.
Any suggestion or next steps.

**Comment by SA-al-000** [comment]
Also the permissions are on for Appyflowy.
