### ISSUE TITLE
[FR] Publish a page

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#716]
Publish an appflowy page to the web

**Comment by almereyda** [comment]
This is now partially available since v0.6.3

- https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.6.3

There is a limitation for self-hosters, that the option is offered in AppFlowy, but breaks, due to generating false-positive URLs when being logged on to a self-hosted AppFlowy Cloud instance.

![grafik](https://github.com/AppFlowy-IO/AppFlowy-Cloud/assets/1645308/bbfa24b5-39d5-4b40-8815-50f79766874b)

Also see:

- https://github.com/AppFlowy-IO/AppFlowy-Cloud/issues/680

**Comment by SkyLostTR** [comment]
Is it on the roadmap for self-hosters? That would be great. HTML Export is buggy sadly as well.

Thanks to all who in this project.
