### ISSUE TITLE
[Bug] Cannot backspace and delete contents in Doc

### ISSUE THREAD

**Issue by ChenTaHung** [AppFlowy-IO/AppFlowy#894]
**Describe the bug**
I can't delete the contents using del button or Backspace in Doc. Keep typing and enter to jump to the next line both work fine. Only when using a Doc file, the backspace and del is not working.
The only way to revise the content for my situation is to select and highlight the words and replace them directly.

**To Reproduce**
1. Click `New page` 
2. add a page and select `Doc`
3. type any word and cannot delete the contents.

**Expected behavior**
Adding a `Grid` page works perfectly fine. I can use backspace to remove the words or use del button to delete the letters. But not for the `Doc` page.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 
 - Version: 12.3.1
 - Chip: Apple M1 Pro

**Additional context**
I followed the instruction on the official documentation to install Appflowy using `$ brew install appflowy`.

Besides the backspace and del issue, `command + A` to select all doesn't work in `Doc` page too.

AppFlowy version : 0.0.4

**Comment by IMPranshu** [comment]
Can You provide a small video of the error that you are facing because in y machine it is working fine?
(random text)
![image](https://user-images.githubusercontent.com/43396684/186227515-fc140eb1-6ba3-4e02-8bed-601bd83e1991.png)
(cleard some texts using backspace)
![image](https://user-images.githubusercontent.com/43396684/186227552-a1b210ba-e844-4858-baa4-461f69cfb9c4.png)

**Comment by ChenTaHung** [comment]
https://user-images.githubusercontent.com/49839507/186301302-d3bb847b-43a9-4179-ba8d-ba143d73355a.mp4

In the video, we can see that the backspace and del work well when using a keyboard test website, but not in AppFlowy. The only way to delete the words is to select the words and replace them by typing another word.
But I found something that might be the reason is that, when I rebooted my computer, AppFlowy works fine when I only type English. However, when I started to type Chinese (in Taiwan we mostly use `ㄅㄆㄇㄈ` to spell Chinese), the issue jumped out. I think the problem might be the `ㄅㄆㄇㄈ` character used to spell Chinese.

**Comment by annieappflowy** [comment]
@IMPranshu @ChenTaHung  thanks for providing more details. This will be fixed in [v0.0.7](https://github.com/orgs/AppFlowy-IO/projects/5)
This is a known issue in flutter_quill, a third-party package we're using. We're switching to our in-house editor, appflowy_editor and will replace flutter_quill in the upcoming releases. [appflowy_editor](https://pub.dev/packages/appflowy_editor) doesn't have this issue.

**Comment by annieappflowy** [comment]
Have you guys checked out our latest [release](https://github.com/AppFlowy-IO/AppFlowy/releases)?
Is this issue fixed? @LucasXu0

**Comment by ChenTaHung** [comment]
@annieappflowy 
Deleting the characters works fine on v0.0.6.2, but it comes out new issues.

It cannot press `capslock` to switch language, and Mandarin typing issues. Do I need to open a new issue?

**Comment by annieappflowy** [comment]
Yes, please. Thank you @ChenTaHung
